In [ ]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split


In [ ]:
#Set display Option
pd.set_option('display.max_columns', None)

In [ ]:
#Load Dataset
from sklearn.datasets import load_breast_cancer

In [ ]:
data = load_breast_cancer()
print(data)


{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [ ]:
x = data.data
print(x)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [ ]:
y = data.target
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [ ]:
#shape of x
x.shape #features = 30

(569, 30)

In [ ]:
#shape of y
y.shape


(569,)

In [ ]:
#Standardize data to normal/guassian distribution
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)


In [ ]:
# x_scaled =StandardScaler().fit_transform(x)

In [ ]:
#OUTLIER DETECTION

##Z-SCORE
from scipy import stats

z_scores = np.abs(stats.zscore(x_scaled))
threshold = 3
outliers = np.where(z_scores > 3)

print("Indices of Outliers in first column: ", np.unique(outliers[0]))

print("Indices of Outliers in second column: ", np.unique(outliers[1]))


Indices of Outliers in first column:  [  0   3   9  12  14  23  25  31  35  42  60  68  71  72  78  82  83 105
 108 112 116 119 122 138 146 151 152 176 180 181 190 192 202 203 212 213
 219 232 236 239 258 259 265 288 290 314 318 323 339 345 351 352 368 370
 376 379 388 389 400 416 417 430 461 473 503 504 505 521 557 559 561 562
 567 568]
Indices of Outliers in second column:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 28 29]


In [ ]:
##IQR(Inter Quartile Range)
Q1 = np.percentile(x_scaled, 25, axis = 0)
Q3 = np.percentile(x_scaled, 75, axis = 0)

IQR = Q3 - Q1

outliers1 = ((x_scaled < (Q1 - 1.5* IQR)) | (x_scaled > (Q3 + 1.5*IQR)))
outliers1 = ((x_scaled < (Q1 - 1.5* IQR)) | (x_scaled > (Q3 + 1.5*IQR))).any(axis=1) #visualize outliers in one dimension

print("Indices of Outliers: ", np.where(outliers1))


Indices of Outliers:  (array([  0,   1,   2,   3,   4,   5,   8,   9,  12,  14,  15,  18,  22,
        23,  24,  25,  26,  27,  30,  31,  33,  34,  35,  38,  41,  42,
        53,  56,  60,  62,  63,  68,  70,  71,  72,  76,  77,  78,  82,
        83,  95, 105, 108, 110, 111, 112, 116, 118, 119, 121, 122, 136,
       138, 145, 146, 147, 150, 151, 152, 156, 161, 162, 164, 168, 173,
       176, 180, 181, 185, 190, 192, 196, 199, 202, 203, 210, 212, 213,
       214, 218, 219, 229, 232, 236, 239, 242, 245, 250, 252, 254, 256,
       257, 258, 259, 262, 265, 272, 273, 275, 288, 290, 300, 302, 314,
       318, 323, 329, 332, 335, 337, 339, 343, 345, 351, 352, 366, 368,
       369, 370, 372, 373, 376, 379, 388, 389, 391, 393, 400, 416, 417,
       424, 430, 433, 443, 449, 450, 455, 460, 461, 465, 468, 469, 471,
       473, 485, 489, 492, 498, 503, 504, 505, 507, 520, 521, 528, 533,
       535, 537, 538, 539, 553, 556, 557, 559, 561, 562, 563, 564, 565,
       567, 568]),)


In [ ]:
##ISOLATION FOREST METHOD
from sklearn.ensemble import IsolationForest

In [ ]:
#Initialise Model
iso_forest = IsolationForest(contamination = 0.01)
#conatmination parameter determines the maximum outlier, here 0.01 means 1% of the outliers


In [ ]:
prediction = iso_forest.fit_predict(x_scaled)
#1s are normal, -1s are outliers


In [ ]:
# predictions = IsolationForest(contamination = 0.1).fit_predict(x_scaled)


In [ ]:
#get outliers
outliers2_indices = np.where(prediction == -1)
print("Indices of Outliers: ", outliers2_indices[0])


Indices of Outliers:  [  3  78 108 122 212 461]


In [ ]:
##LOCAL OUTLIER FACTOR METHOD
from sklearn.neighbors import LocalOutlierFactor

LOF = LocalOutlierFactor(n_neighbors=20, contamination=0.01) #initialization

predict = LOF.fit_predict(x_scaled)

# LOF = LocalOutlierFactor(n_neighbors=20, contamination=0.01).fit_predict(x_scaled)


In [ ]:
#get outliers
outliers3 = np.where(predict == -1)
print("Indices of Outliers: ", outliers3)
# print("Indices of Outliers: ", outliers3[0])



Indices of Outliers:  (array([ 38, 152, 192, 212, 213, 461]),)


In [ ]:
##DBSCAN
from sklearn.cluster import DBSCAN

In [ ]:
DBSCAN = DBSCAN(eps = 5, min_samples = 5)
clusters = DBSCAN.fit_predict(x_scaled)


In [ ]:
# clusters = DBSCAN(eps = 0.5, min_samples = 5).fit_predict(x_scaled)


In [ ]:
#get outliers
outliers4_indices = np.where(clusters == -1)
print("Indices of Outliers:", outliers4_indices)


Indices of Outliers: (array([  3,   9,  12,  42,  68,  71,  78,  83, 108, 122, 138, 152, 176,
       190, 192, 212, 213, 258, 288, 290, 314, 461, 504, 505]),)


In [ ]:
##ONE-CLASS SVM
from sklearn.svm import OneClassSVM

oc_svm = OneClassSVM(nu=0.01, kernel='rbf', gamma=0.1)
oc_svm.fit(x_scaled)
predict1 = oc_svm.predict(x_scaled)


In [ ]:
#get outliers
outliers5_indices = np.where(predict == 1 )
print("Indices of Outliers:", outliers5_indices)

Indices of Outliers: (array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 153, 154, 155, 156, 157,
       158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
       171, 172, 173, 174, 175, 176, 177, 

In [ ]:
## MOHALANOBIS DISTANCE
from scipy.spatial import distance


In [ ]:
#inverse covariance matrix
cov_matrix = np.cov(x_scaled.T)
inv_cov_matrix = np.linalg.inv(cov_matrix)


In [ ]:
# Calculate Distance
mean_vals = np.mean(x_scaled, axis=0)
distance = np.array([distance.mahalanobis(x, mean_vals, inv_cov_matrix)for x in x_scaled])

In [ ]:
# store = []
# for x in x_scaled:
#     store.append(distance.mahalanobis(x, mean_vals, inv_cov_matrix))
# print(len(store))

# mahalanobis_distance1 = np.array(store)


In [ ]:
threshold = np.mean(distance) + 3 * np.std(distance)
outliers6_indices = np.where(distance > threshold)
print("Indices Of Outliers: ", outliers6_indices[0])



Indices Of Outliers:  [  9  12  38  68  71  78 122 152 192 212 213 265 290 461]


In [ ]:
!pip install tensorflow

In [ ]:
##AUTOENCODER
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input


In [ ]:
#define autoencoder architect
model = Sequential([
    Input(shape=(x_scaled.shape[1]), ),
          Dense(16, activation ='relu'),
          Dense(8, activation = 'relu'),
          Dense(4, activation = 'relu'),
          Dense(2,activation='relu'), #compressed representation
          Dense(4, activation='relu'),
          Dense(8, activation = 'relu'),
          Dense(16, activation='relu'),
          Dense(x_scaled.shape[1], activation = 'linear') #reconstruction
          ])

model.compile(optimizer = 'adam', loss = 'mse')
model.fit(x_scaled, x_scaled, epochs=1, batch_size=16, validation_split=0.1)


32/32 [==============================] - 2s 10ms/step - loss: 1.0257 - val_loss: 0.9056


In [ ]:
#predict the reconstruction error
reconstruction = model.predict(x_scaled)
mse = np.mean(np.power(x_scaled - reconstruction, 2), axis = 1)


18/18 [==============================] - 0s 2ms/step


In [ ]:
#Detect Outliers
mse_threshold = np.quantile(mse, 0.99)
outliers7_indices = np.where(mse > mse_threshold)
print('Indices of Outliers: ', outliers7_indices[0])


Indices of Outliers:  [  3  78 122 152 212 461]
